name: Publish Website

on:
    push:
        branches:
            - main
    workflow_dispatch:
jobs:
    Build-Artifact-Action:
        name: Build-Artifact-Action
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@master
            - uses: actions/setup-node@v4
              with:
                  node-version: 20
                  cache: 'npm'
            - run: npm install
            - run: npm run build
            - name: Upload the artifact
              uses: actions/upload-artifact@v4
              with:
                  name: wpcom
                  path: |
                      .
                      !style.css 
                      !node_modules
                      !README.md
                      !package.json
                      !package-lock.json
                      !.editorconfig
                      !.git
                      !.gitignore
                      !src
                      !webpack.config.js
